### ISSUE TITLE
Support custom API

### ISSUE THREAD

**Issue by kotobuki09** [CCCBora/auto-draft#13]
Could you make it support custom API? 
I currently use Azure OpenAI example.

**Comment by CCCBora** [comment]
Yes, I have a plan to support that. If you need that immediately, you can find the class [GPTModel_API2D_SUPPORT](https://github.com/CCCBora/auto-draft/tree/main/utils/gpt_interaction.py) in `utils/gpt_interaction.py`; it should be compatiable with Azure OpenAI API by changing `url="https://api.openai.com/v1/chat/completions"` to your own endpoint.

**Comment by hooli67** [comment]
just set openai.api_base and openai.api_key

**Comment by CCCBora** [comment]
> just set openai.api_base and openai.api_key

Thanks for pointing it out! I just added the following codes in `app.py` to support the Azure OpenAI API endpoint.
```
openai_api_base = os.getenv("OPENAI_API_BASE")
if openai_api_base is not None:
    openai.api_base = openai_api_base
```
