### ISSUE TITLE
Can you tell me how to set OPENAI_API_KEY?

### ISSUE THREAD

**Issue by doublepoints** [CCCBora/auto-draft#4]
Thank you for your time.
I am trying your project.
However, I do not konw how to set openai_api_key, would you tell me the details?

Besr regards

**Comment by CCCBora** [comment]
> 

Thanks! The usage section has been outdated; I will update it soon! 

Currently, you can mannually modify `app.py`. Change this line
```openai_key = os.getenv("OPENAI_API_KEY")```
to the following (change it to your key)
```openai_key = "sk-ASji1kXICJkd2LKXdxdf9SAKDFL241dsfSKdsfjoikjesmSK"```

Note that all current codes rely on the GPT-4 access. If you are not sure if your key has GPT-4 avaiability, you may check your mailbox to see if there is an email saying "Your GPT-4 API invite is here"or using this tool [https://huggingface.co/spaces/shaocongma/openai_api_key_status](https://huggingface.co/spaces/shaocongma/openai_api_key_status).

**Comment by buaaguotong** [comment]
您好。
已经开通了gpt4，在官网上获得了api key并成功运行代码。但是报错如下：
The paper information has been initialized. References are saved to outputs/outputs_20230613_224856/ref.bib.
Loaded as API: https://shaocongma-evaluate-specter-embeddings.hf.space/ ✔
================PROCESSING================
Generate introduction part...
Failed to generate introduction. InvalidRequestError was raised:  The model: `gpt-4` does not exist

Failed to generate introduction. InvalidRequestError was raised:  The model: `gpt-4` does not exist

Failed to generate introduction. InvalidRequestError was raised:  The model: `gpt-4` does not exist

Failed to generate introduction. InvalidRequestError was raised:  The model: `gpt-4` does not exist


是不是key获取的方式不对？
